namespace Marqdouj.DotNet.Web.Components.Css
{
    public static class HtmlColorNameExtensions
    {
        /// <summary>
        /// Returns the Hex string for the HtmlColorName.
        /// </summary>
        /// <param name="colorName"></param>
        /// <returns></returns>
        /// <exception cref="ArgumentOutOfRangeException"></exception>
        public static string ToHex(this HtmlColorName colorName)
        {
            return colorName switch
            {
                HtmlColorName.AliceBlue => "#F0F8FF",
                HtmlColorName.AntiqueWhite => "#FAEBD7",
                HtmlColorName.Aqua => "#00FFFF",
                HtmlColorName.Aquamarine => "#7FFFD4",
                HtmlColorName.Azure => "#F0FFFF",
                HtmlColorName.Beige => "#F5F5DC",
                HtmlColorName.Bisque => "#FFE4C4",
                HtmlColorName.Black => "#000000",
                HtmlColorName.BlanchedAlmond => "#FFEBCD",
                HtmlColorName.Blue => "#0000FF",
                HtmlColorName.BlueViolet => "#8A2BE2",
                HtmlColorName.Brown => "#A52A2A",
                HtmlColorName.BurlyWood => "#DEB887",
                HtmlColorName.CadetBlue => "#5F9EA0",
                HtmlColorName.Chartreuse => "#7FFF00",
                HtmlColorName.Chocolate => "#D2691E",
                HtmlColorName.Coral => "#FF7F50",
                HtmlColorName.CornflowerBlue => "#6495ED",
                HtmlColorName.Cornsilk => "#FFF8DC",
                HtmlColorName.Crimson => "#DC143C",
                HtmlColorName.Cyan => "#00FFFF",
                HtmlColorName.DarkBlue => "#00008B",
                HtmlColorName.DarkCyan => "#008B8B",
                HtmlColorName.DarkGoldenRod => "#B8860B",
                HtmlColorName.DarkGray => "#A9A9A9",
                HtmlColorName.DarkGrey => "#A9A9A9",
                HtmlColorName.DarkGreen => "#006400",
                HtmlColorName.DarkKhaki => "#BDB76B",
                HtmlColorName.DarkMagenta => "#8B008B",
                HtmlColorName.DarkOliveGreen => "#556B2F",
                HtmlColorName.DarkOrange => "#FF8C00",
                HtmlColorName.DarkOrchid => "#9932CC",
                HtmlColorName.DarkRed => "#8B0000",
                HtmlColorName.DarkSalmon => "#E9967A",
                HtmlColorName.DarkSeaGreen => "#8FBC8F",
                HtmlColorName.DarkSlateBlue => "#483D8B",
                HtmlColorName.DarkSlateGray => "#2F4F4F",
                HtmlColorName.DarkSlateGrey => "#2F4F4F",
                HtmlColorName.DarkTurquoise => "#00CED1",
                HtmlColorName.DarkViolet => "#9400D3",
                HtmlColorName.DeepPink => "#FF1493",
                HtmlColorName.DeepSkyBlue => "#00BFFF",
                HtmlColorName.DimGray => "#696969",
                HtmlColorName.DodgerBlue => "#1E90FF",
                HtmlColorName.FireBrick => "#B22222",
                HtmlColorName.FloralWhite => "#FFFAF0",
                HtmlColorName.ForestGreen => "#228B22",
                HtmlColorName.Fuchsia => "#FF00FF",
                HtmlColorName.Gainsboro => "#DCDCDC",
                HtmlColorName.GhostWhite => "#F8F8FF",
                HtmlColorName.Gold => "#FFD700",
                HtmlColorName.GoldenRod => "#DAA520",
                HtmlColorName.Gray => "#808080",
                HtmlColorName.Grey => "#808080",
                HtmlColorName.Green => "#008000",
                HtmlColorName.GreenYellow => "#ADFF2F",
                HtmlColorName.HoneyDew => "#F0FFF0",
                HtmlColorName.HotPink => "#FF69B4",
                HtmlColorName.IndianRed => "#CD5C5C",
                HtmlColorName.Indigo => "#4B0082",
                HtmlColorName.Ivory => "#FFFFF0",
                HtmlColorName.Khaki => "#F0E68C",
                HtmlColorName.Lavender => "#E6E6FA",
                HtmlColorName.LavenderBlush => "#FFF0F5",
                HtmlColorName.LawnGreen => "#7CFC00",
                HtmlColorName.LemonChiffon => "#FFFACD",
                HtmlColorName.LightBlue => "#ADD8E6",
                HtmlColorName.LightCoral => "#F08080",
                HtmlColorName.LightCyan => "#E0FFFF",
                HtmlColorName.LightGoldenRodYellow => "#FAFAD2",
                HtmlColorName.LightGray => "#D3D3D3",
                HtmlColorName.LightGrey => "#D3D3D3",
                HtmlColorName.LightGreen => "#90EE90",
                HtmlColorName.LightPink => "#FFB6C1",
                HtmlColorName.LightSalmon => "#FFA07A",
                HtmlColorName.LightSeaGreen => "#20B2AA",
                HtmlColorName.LightSkyBlue => "#87CEFA",
                HtmlColorName.LightSlateGray => "#778899",
                HtmlColorName.LightSlateGrey => "#778899",
                HtmlColorName.LightSteelBlue => "#B0C4DE",
                HtmlColorName.LightYellow => "#FFFFE0",
                HtmlColorName.Lime => "#00FF00",
                HtmlColorName.LimeGreen => "#32CD32",
                HtmlColorName.Linen => "#FAF0E6",
                HtmlColorName.Magenta => "#FF00FF",
                HtmlColorName.Maroon => "#800000",
                HtmlColorName.MediumAquaMarine => "#66CDAA",
                HtmlColorName.MediumBlue => "#0000CD",
                HtmlColorName.MediumOrchid => "#BA55D3",
                HtmlColorName.MediumPurple => "#9370DB",
                HtmlColorName.MediumSeaGreen => "#3CB371",
                HtmlColorName.MediumSlateBlue => "#7B68EE",
                HtmlColorName.MediumSpringGreen => "#00FA9A",
                HtmlColorName.MediumTurquoise => "#48D1CC",
                HtmlColorName.MediumVioletRed => "#C71585",
                HtmlColorName.MidnightBlue => "#191970",
                HtmlColorName.MintCream => "#F5FFFA",
                HtmlColorName.MistyRose => "#FFE4E1",
                HtmlColorName.Moccasin => "#FFE4B5",
                HtmlColorName.NavajoWhite => "#FFDEAD",
                HtmlColorName.Navy => "#000080",
                HtmlColorName.OldLace => "#FDF5E6",
                HtmlColorName.Olive => "#808000",
                HtmlColorName.OliveDrab => "#6B8E23",
                HtmlColorName.Orange => "#FFA500",
                HtmlColorName.OrangeRed => "#FF4500",
                HtmlColorName.Orchid => "#DA70D6",
                HtmlColorName.PaleGoldenRod => "#EEE8AA",
                HtmlColorName.PaleGreen => "#98FB98",
                HtmlColorName.PaleTurquoise => "#AFEEEE",
                HtmlColorName.PaleVioletRed => "#DB7093",
                HtmlColorName.PapayaWhip => "#FFEFD5",
                HtmlColorName.PeachPuff => "#FFDAB9",
                HtmlColorName.Peru => "#CD853F",
                HtmlColorName.Pink => "#FFC0CB",
                HtmlColorName.Plum => "#DDA0DD",
                HtmlColorName.PowderBlue => "#B0E0E6",
                HtmlColorName.Purple => "#800080",
                HtmlColorName.RebeccaPurple => "#663399",
                HtmlColorName.Red => "#FF0000",
                HtmlColorName.RosyBrown => "#BC8F8F",
                HtmlColorName.RoyalBlue => "#4169E1",
                HtmlColorName.SaddleBrown => "#8B4513",
                HtmlColorName.Salmon => "#FA8072",
                HtmlColorName.SandyBrown => "#F4A460",
                HtmlColorName.SeaGreen => "#2E8B57",
                HtmlColorName.SeaShell => "#FFF5EE",
                HtmlColorName.Sienna => "#A0522D",
                HtmlColorName.Silver => "#C0C0C0",
                HtmlColorName.SkyBlue => "#87CEEB",
                HtmlColorName.SlateBlue => "#6A5ACD",
                HtmlColorName.SlateGray => "#708090",
                HtmlColorName.SlateGrey => "#708090",
                HtmlColorName.Snow => "#FFFAFA",
                HtmlColorName.SpringGreen => "#00FF7F",
                HtmlColorName.SteelBlue => "#4682B4",
                HtmlColorName.Tan => "#D2B48C",
                HtmlColorName.Teal => "#008080",
                HtmlColorName.Thistle => "#D8BFD8",
                HtmlColorName.Tomato => "#FF6347",
                HtmlColorName.Turquoise => "#40E0D0",
                HtmlColorName.Violet => "#EE82EE",
                HtmlColorName.Wheat => "#F5DEB3",
                HtmlColorName.White => "#FFFFFF",
                HtmlColorName.WhiteSmoke => "#F5F5F5",
                HtmlColorName.Yellow => "#FFFF00",
                HtmlColorName.YellowGreen => "#9ACD32",
                _ => throw new ArgumentOutOfRangeException(nameof(colorName), colorName, null)
            };
        }
    }
}
